{{- $email := .Values.email -}}
{{- $release := .Release -}}

{{- range $issuer := .Values.issuers }}
---
apiVersion: cert-manager.io/v1alpha2
kind: {{ .kind }}
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: {{ template "cert-manager-issuers.name" $ }}
    chart: {{ template "cert-manager-issuers.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  acme:
    server: {{ .server }}
    {{- if .email }}
    email: {{ .email }}
    {{- else }}
    email: {{ $email }}
    {{- end }}
    privateKeySecretRef:
      name: {{ .name }}
{{ toYaml .method | indent 4 }}

{{- end }}
