steps:
- name: 'gcr.io/cloud-builders/go:alpine'
  entrypoint: 'bash'
  args: [
    'env'
    ]
  env:
  - 'GITHUB_USER=${_GITHUB_USER}' #specify as a GCB substitution
  - 'GITHUB_REPO=${REPO_NAME}'

- name: 'gcr.io/cloud-builders/go:alpine'
  entrypoint: 'bash'
  args: [
    'make',
    'deps dist'
    ]
  env:
  - 'GITHUB_USER=${_GITHUB_USER}' #specify as a GCB substitution
  - 'GITHUB_REPO=${REPO_NAME}'
  secretEnv:
  - 'GITHUB_TOKEN'

secrets:
- kmsKeyName: projects/$PROJECT_ID/locations/global/keyRings/$PROJECT_ID/cryptoKeys/cloudbuild
  secretEnv:
    GITHUB_TOKEN: CiQA7J4wCQjxDPi/CpckwurLwS+7SIF7/RmhNxZWwei9voaMsK4SUQCQvfKNybVsrtJdOWDvGUn0o1XZ5iZLonw9ASkQW+V1s/NHlSfGfjsHDpjrx43CldNm0t6YcrMxhACki0M+MhFMc6y7ky4DCxUFF4ffQUEidg==
