name: cert-manager-issuers
version: v0.0.4
description: A Helm chart for cert-manager issuers
home: https://github.com/afirth/site-cluster
keywords:
  - cert-manager
  - kube-lego
  - letsencrypt
  - tls
  - clusterissuer
maintainers:
  - name: afirth
    email: maintainer@alfirth.com
